- name: Install nginx web server
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Make sure nginx is started
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started 
